# Generated by Django 5.1.2 on 2024-10-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
