# Generated by Django 5.1.3 on 2024-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_seo_description_alter_news_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
